version: '3.8'
services:
  url-shorter:
    container_name: url-shorter
    image: ghcr.io/marcolenschau/url-shorter:latest
    hostname: url-shorter
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: url-shorter-db
    image: mongo:latest
    hostname: db
    restart: on-failure
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}